use mmfb;
db.dropDatabase();

db.users.insertMany([
    {username: "MemeQueen5000",
    email: "memequeen5000@mememail.com",
    password: "memesarelife", 
    },
    {username: "MemeLord1",
    email: "memelord@mememail.com",
    password: "password123", 
    },
    {username: "everythingsfine",
    email: "itsnotreally@mememail.com",
    password: "password321", 
    },
]);

use memeLibrary;
db.dropDatabase();

db.memes.insertMany([
    {name: "add css",
    catagory: "css",
    url: "https://images.app.goo.gl/HW3VnSU96fN1sc6f9",  
    },
    {name: "pikachu",
    catagory: "css",
    url: "https://images.app.goo.gl/cqE4bo13TbdTUCnB9",  
    }, 
    {name: "one does not",
    catagory: "css",
    url: "https://images.app.goo.gl/vVA1sHb4N19vFrL89",  
    },
    {name: "family guy",
    catagory: "css",
    url: "https://images.app.goo.gl/LHSNSMjidUcc2c9J6",  
    },
    {name: "are you ok?",
    catagory: "ugood?",
    url: "https://images.app.goo.gl/QoLrHceVWZfnyHB47",  
    },
    {name: "u good baby",
    catagory: "ugood?",
    url: "https://images.app.goo.gl/gdUmAwK1GEiSU6317",  
    },
    {name: "u good cats",
    catagory: "ugood?",
    url: "https://images.app.goo.gl/AE15itRrr3xsCE7k8",  
    },
    {name: "u good shark",
    catagory: "ugood?",
    url: "https://images.app.goo.gl/JXQcmTApC2V9s3QF9",  
    },
    {name: "inbred",
    catagory: "cats",
    url: "https://images.app.goo.gl/4q8LEwoQCXEVKgKx8",  
    },
    {name: "boobytrap",
    catagory: "cats",
    url: "https://images.app.goo.gl/NmAiqhL4oQdopS126",  
    },
    {name: "screaming cat",
    catagory: "cat",
    url: "https://images.app.goo.gl/A4KftyDk47zBqfMB8",  
    },
    {name: "staring cat",
    catagory: "cat",
    url: "https://images.app.goo.gl/NLTdnVBLp7MESKZr5",  
    },
    {name: "success kid",
    catagory: "sucsess",
    url: "https://images.app.goo.gl/rMR5rr6uvBYYpyyz9",  
    },
    {name: "borat",
    catagory: "success",
    url: "https://images.app.goo.gl/t6KjLtWLwuNCp1M1A",  
    },
    {name: "squirrel",
    catagory: "success",
    url: "https://images.app.goo.gl/ECTeBQAv1nieqQvJ8",  
    },
    {name: "gordon",
    catagory: "sucess",
    url: "https://images.app.goo.gl/qPn9XAR7xjGh9toc8",  
    },
    {name: "success cat",
    catagory: "sucess",
    url: "https://images.app.goo.gl/DwDCodmnwCPAYRBD8",  
    },
    {name: "you look good",
    catagory: "looks",
    url: "https://media.tenor.com/3dV00F9O3BkAAAAC/ohhhahhhhh-wow.gif",  
    },
    {name: "ohhhhhh",
    catagory: "funny",
    url: "https://media.tenor.com/T8NUkKuaGAsAAAAC/ohhh-whoah.gif",  
    },
    {name: "bunny",
    catagory: "looks",
    url: "https://media.tenor.com/M6tmbMOzYxcAAAAd/yup-you-look-beautiful.gif",  
    },
    {name: "good job",
    catagory: "success",
    url: "https://media.tenor.com/sIzMTGPxIeMAAAAd/well-done.gif",  
    },
    {name: "hey king",
    catagory: "hello",
    url: "https://media.tenor.com/GAwMGtOaLVYAAAAC/value-select-hey-king.gif",  
    },
    {name: "sparkles",
    catagory: "success",
    url: "https://media.tenor.com/F-mq05c3FUIAAAAC/celebrate-confetti.gif",  
    },
    {name: "yass queen",
    catagory: "success",
    url: "https://media.tenor.com/ACthELqvQ5MAAAAC/ray-holt-yas-queen.gif",  
    },
    {name: "waving penguin",
    catagory: "hello",
    url: "https://media.tenor.com/ACthELqvQ5MAAAAC/ray-holt-yas-queen.gif",  
    },
    {name: "hey jimmy",
    catagory: "hello",
    url: "https://media.tenor.com/ACthELqvQ5MAAAAC/ray-holt-yas-queen.gif",  
    },
    {name: "rough day?",
    catagory: "here for you",
    url: "https://images.app.goo.gl/FjWJnVLU6NrHSUqs5",  
    },
    {name: "doggos",
    catagory: "here for you",
    url: "https://images.app.goo.gl/tsy4xbBx4drLWtGYA",  
    },
    {name: "it",
    catagory: "here for you",
    url: "https://images.app.goo.gl/QEBDLrTPYstE6gY5A",  
    },
    {name: "bob",
    catagory: "ugood?",
    url: "https://images.app.goo.gl/rdnwpFoQfGRcoAB7A",  
    }
])